openai_key = "key" 
chat_url = "url"
model_name = "model_name"
proxy = false
support_tool = true # if support tool call

[mcp]
[[mcp.server]]
name = "MCP server name"
protocol = "stdio"
command = "MCP server path"
args = [" "]